schema_version: 2024.04.01
type: job
spec:
  name: causal-shift-train2-test3
  owner: dgm-ms-brain-mri/pedro-maciasgordaliza
  description: 'Causal mechanism shift analysis from annotator 2 to annotator 3'
  image: dgm-ms-brain-mri/pedro-maciasgordaliza/seg_model_attr:0.0.3
  instance_type: 1xA100
  environment_variables:
    TRAIN_ANNOTATOR: "2"
    TEST_ANNOTATOR: "3"
    NNUNET_FOLDERS_PATH: "/home/jovyan/shared/pedro-maciasgordaliza/ms-data/nnunet_folders"
    NUM_EPOCHS: "1"
    DEVICE: "cuda"
    N_JOBS: "1"
    SHAPLEY_SAMPLES: "500"
  working_directory: /home/jovyan/workspace/CausalDropMedImg
  command: 'python attributions/examples/medical_image_call.py --train_annotator 2 --test_annotator 3 --nnunet_folders_path $NNUNET_FOLDERS_PATH --num_epochs $NUM_EPOCHS --device $DEVICE --n_jobs $N_JOBS --shapley_samples $SHAPLEY_SAMPLES && sc stop job causal-shift-train2-test3'
  scale: 1
  use_spot_instance: false
  schedule: null
  shared_folders:
    - owner: dgm-ms-brain-mri/pedro-maciasgordaliza
      path: /home/jovyan/shared/pedro-maciasgordaliza/ms-data
      name: ms-data